name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Build and test components
        run: |
          cd IPS/Consumer
          docker build -t consumer .
          cd ..
          cd Producer
          docker build -t producer .
          cd ..
          cd SeleniumApp
          docker build -t seleniumapp .
          cd ../..

      - name: Run tests
        run: |
          cd IPS/Consumer
          docker run consumer python -m pytest
          cd ..
          cd Producer
          docker run producer python -m pytest
          cd ..
          cd SeleniumApp
          docker run seleniumapp python -m pytest
          cd ..


